import { useDispatch, useSelector } from "react-redux";
// import { counterSlice, CounterState, store } from "./_app";
import { NextPage } from "next";
import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import liff from '@line/liff';

import FirebaseAuthGoogleButton from '../src/firebase/FirebaseAuthGoogleButton';
import FirebaseAuthSignoutButton from '../src/firebase/FirebaseAuthSignoutButton';
import FirestoreAddButton from '../src/firebase/FirestoreAddButton';
import FirestoreList from '../src/firebase/FirestoreList';
import { initializeApp, getApps } from "firebase/app"


import { RootState } from '../src/store'
import { userSlice } from '../src/store/user'


const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_APIKEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTHDOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECTID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGEBUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APPID,
  measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENTID
};

const app = getApps
if (app.length === 0) {
  initializeApp(firebaseConfig)
}
console.log('firebase', firebaseConfig)

const lineClick = function () {
  // onloadd()
  // liff.login();
  window.location.href = loginUrl;
};
const loginUrl = "https://access.line.me/oauth2/v2.1/authorize?app_id=1656149559-xXM4l4Gp&client_id=1656149559&scope=chat_message.write+openid+profile&state=MTSFhIGGxsff&bot_prompt=aggressive&response_type=code&code_challenge_method=S256&code_challenge=Hx-YFyPAvO9ZQIg5pQpaGQuMChsOE11Raf_3DHDGFgY&liff_sdk_version=2.11.1&type=L&redirect_uri=https%3A%2F%2Fkonoyubi.site%2F"







const Home: NextPage = () => {

  const dispatch = useDispatch()
  const user = useSelector((state: RootState) => state.user)

  const handleConfirm = () => {
    // eslint-disable-next-line
    console.log(user)
  }
  const handleUpdate = () => {
    dispatch(
      userSlice.actions.updateUser({
        name: 'name',
        age: 28,
        email: 'email',
        token: 'token',
        history: [],
      })
    )
  }
  const handleReset = () => {
    dispatch(userSlice.actions.reset())
  }
  const handleAddHistory = () => {
    dispatch(userSlice.actions.addHistory('push'))
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://konoyubi.site">konoyubi</a>
        </h1>
        <section className="h-screen w-4/5 max-w-5xl mx-auto flex items-center justify-center flex-col">
          <button onClick={lineClick}>
            <h1 className="mb-4 text-green-500 text-3xl">ログイン</h1>
          </button>
          <p className="mb-2 text-center">sample text</p>
          <button className="btn-blue">Let's Start!!</button>
        </section>

        <h1>storeの動作確認</h1>
        <button type="button" onClick={handleConfirm}>
          確認
        </button>
        <button type="button" onClick={handleUpdate}>
          update
        </button>
        <button type="button" onClick={handleReset}>
          reset
        </button>
        <button type="button" onClick={handleAddHistory}>
          addHistory
        </button>
        <FirebaseAuthGoogleButton />
        <FirebaseAuthSignoutButton />
        {/* <FirestoreAddButton /> */}
        <FirestoreList />

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>

  );
};

export default Home;